version: '3.8'

services: 
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dapos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker

  mvp:
     build: .
     volumes: 
         - .:/app
     command: python3 manage.py runserver 0.0.0.0:8000
     ports: 
         - 8000:8000
     env_file:
         - ./.env
     depends_on:
         - db
