name: Code Quality

on:
  push:
    branches-ignore:
      - master

jobs:
  checks:
    name: Lint and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
        export ENVIORMENT=TEST

    - name: Run Prospector linter
      run: |
        export DJANGO_SETTINGS_MODULE=dapos_server.settings
        poetry run prospector
    - name: Run Black (formatting) linter
      run: |
        poetry run black --check .
